export const PLAYER_DISCORD_MAP: { discord: string; player: string }[] = [
  { discord: 'drakken682', player: 'Drakken' },
  { discord: '.xxxgamer69xxx', player: 'xXXwamts69XXx' },
  { discord: 'b0romir', player: 'Boromir' },
  { discord: 'evil_pirate.', player: 'alexisfougeres' },
  { discord: '.tbp113', player: 'TheSandMan' },
  { discord: 'yaveshc', player: 'Nelly' },
  { discord: 'beelard', player: 'phuhoang117' },
  { discord: 'JimmieG', player: 'JimmieG' },
  { discord: 'unholyjake5622', player: 'Unholyjake' },
  { discord: 'flexsnes', player: 'Flexnes' },
  { discord: 'mushinette', player: 'Mushi' },
  { discord: 'm4r1d_43389', player: 'F3d4yk1n' },
  { discord: 'Wolf_Apostle', player: 'WolfApostle' },
  { discord: 'brax25', player: 'Luckyastro' },
  { discord: 'nana_8764', player: 'Hector' },
  { discord: 'Shanonimous', player: 'shanonimous' },
  { discord: 'raccoon_fan', player: 'Gerry' },
  { discord: 'lucasta143', player: 'Lucasta' },
  { discord: 'sirstanel', player: 'stanel' },
  { discord: 'suav3nanav3', player: 'ImALittleShai' },
  { discord: 'Sdis02', player: 'JordanBardella' },
  { discord: 'jwengelhardt', player: 'JENGEL' },
  { discord: 'lannister2005', player: 'Lannister05' },
  { discord: 'MarvinsQuest', player: 'MarvinsQuest' },
  { discord: 'Varthos', player: 'Varthos' },
  { discord: 'Uldon', player: 'Uldon' },
  { discord: '.omsk', player: 'Riven' },
  { discord: 'plpmrburn', player: 'MrBurn' },
  { discord: 'gabiels', player: 'GabeMagicMaster' },
  { discord: 'unmute', player: 'UnMute' },
  { discord: 'nlbouncyknight', player: 'Bouncyknight' },
  { discord: 'mercury_a', player: 'Mercury' },
  { discord: 'pricelessait', player: 'Priceless' },
  { discord: 'zamba.bone', player: 'Boiler' },
  { discord: 'SquirrelsGoneWild', player: 'SquirrelsGoneWild' },
  { discord: 'daywalker2k21', player: 'daywalker' },
  { discord: 'wil8053', player: 'Khashir' },
  { discord: 'ArthurDee', player: 'ArthurDee' },
  { discord: 'GZUZROCKS', player: 'GZUZROCKS' },
  { discord: 'suproman', player: 'suproman' },
  { discord: 'snube1987', player: 'Snube' },
  { discord: 'mal1982._72261', player: 'Mal1982' },
  { discord: 'halbsodoppelt', player: 'halbsodoppelt' },
  { discord: 'Mchaud', player: 'Mchaud' },
  { discord: 'remarkable91', player: 'ReMarkable' },
  { discord: 'bushidobam', player: 'bushidobam' },
  { discord: 'dfl30008986', player: 'Duffinator' },
  { discord: 'webben', player: 'webben' },
  { discord: 'shaun4ytfc', player: 'shaun4ytfc' },
  { discord: 'bansa_37147', player: 'bansachoding' },
  { discord: 'Mojo810', player: 'Mojo810' },
  { discord: 'lumpyprol', player: 'lumpyprol' },
  { discord: 'garf8621', player: 'Grafik' },
  { discord: 'fumbles2077', player: 'Fumbles' },
  { discord: 'ztu_00', player: 'Stubss' },
  { discord: 'epicericus', player: 'EpicEric' },
  { discord: '_benoah', player: 'Benoa' },
  { discord: 'blackshadow993', player: 'BlackShadow' },
  { discord: 'Horgle', player: 'Horgle' },
  { discord: 'ubermaan', player: 'Ubermaan' },
  { discord: 'presidenttucker', player: 'PresidentTucker' },
  { discord: 'doctorheij9933', player: 'deheij' },
  { discord: 'aspen__18', player: 'aspen' },
  { discord: 'Vitrebreaker', player: 'Vitrebreaker' },
  { discord: 'shadow_knight79', player: 'ShadowKnight' },
  { discord: '.retropanda', player: 'RetroPandroo' },
  { discord: 'Therkis', player: 'Therkis' },
  { discord: 'vasquez5666', player: 'jKeZzZ' },
  { discord: 'Bak_phy', player: 'Bak_phy' },
  { discord: 'beyo77', player: 'Mrooczek' },
  { discord: 'beylur3', player: 'DoNotCopy' },
  { discord: 'kgdl', player: 'KevinL' },
  { discord: 'Nathan_Trade', player: 'Nathan' },
  { discord: 'xsnooks', player: 'JSnooks' },
  { discord: 'badriguez9445', player: 'AbeSkray' },
  { discord: 'eatwellcapemay', player: 'roninwitdadevil' },
  { discord: 'Merkizy', player: 'merkizy' },
  { discord: 'spitfire_33', player: 'Spitfire' },
  { discord: 'Sean909', player: 'shamusj909' },
  { discord: 'markk71.', player: 'MNK71' },
  { discord: 'HearOlexio', player: 'HearOlexio' },
  { discord: 'LordTheRon', player: 'LordTheRon' },
  { discord: 'Alaida_', player: 'Alaida' },
  { discord: '.nail', player: 'DoubleColorless' },
  { discord: 'jwigs13', player: 'jwigs13' },
  { discord: 'hlong1670', player: 'Sbstorm' },
  { discord: 'fatihk92', player: 'FatihK92' },
  { discord: 'HereticD', player: 'HereticD' },
  { discord: 'shipitholla.', player: 'ShipitHolla' },
  { discord: 'greengood', player: 'greengood' },
  { discord: 'rubik4423', player: 'ErnoRuvik' },
  { discord: 'XxShadow_DemonxX', player: 'XxshadowdemonxX' },
  { discord: 'zck', player: 'zzzck' },
  { discord: 'andyisverycool', player: 'AnbyDrown' },
  { discord: 'phan_korbal7653', player: 'Korbal44' },
  { discord: 'jantheman2083', player: 'Janjjd' },
  { discord: '.tsos', player: 'thesonofsaul' },
  { discord: 'mollarom_73', player: 'Mollarom' },
  { discord: 'krang_18323', player: 'krang' },
  { discord: 'smartiniii', player: 'smartini' },
  { discord: 'johnny5ive1438', player: 'J5ive' },
  { discord: 'Opossini', player: 'Oposssini' },
  { discord: 'DarkPortents', player: 'DarkPortents' },
  { discord: '.captdev', player: 'kingdev' },
  { discord: 'arghaghosh12799', player: 'arghaghosh12799' },
  { discord: 'h3llmaker', player: 'H3llm4k3r' },
  { discord: 'K0ncept.', player: 'K0ncept + 4561' },
  { discord: 'nevic_scythe', player: 'Nevic' },
  { discord: 'Sonalator', player: 'Sonalator' },
  { discord: 'daydream13', player: 'Flashwolves' },
  { discord: 'lukondza', player: 'Pariukas' },
  { discord: 'vasilia21613', player: 'Tatiana' },
  { discord: 'Zamalekite', player: 'Zamalekite' },
  { discord: 'awesem', player: 'Awesem' },
  { discord: 'Danmangomez', player: 'ELPPMASGRANDE' },
  { discord: 'cinder0778', player: 'aaagp4' },
  { discord: 'rewindabit', player: 'rewindabit' },
  { discord: 'Coffeebeam', player: 'coffee' },
  { discord: 'Wacky_slush1029', player: 'Dogma' },
  { discord: 'nara5142', player: 'tontonlolo' },
  { discord: 'jack_bauer_24', player: 'JackBauer24' },
  { discord: 'johb_', player: 'JobFR' },
  { discord: 'onlyiwillremain3602', player: 'OnlyiWillRemain' },
  { discord: 'prufrockstar', player: 'Prufrockstar' },
  { discord: 'Double_d_cheme', player: 'DoubleDChemE' },
  { discord: 'riogo_', player: 'RIOGO' },
  { discord: 'Matsand', player: 'Tumregel' },
  { discord: 'Dionprv', player: 'Dionprv' },
  { discord: 'Shakerbaby', player: 'Shakerbaby' },
  { discord: 'swok', player: 'MrHism' },
  { discord: 'xennia_gaming', player: 'Xennia' },
  { discord: 'daveedojr', player: 'daveedojr' },
  { discord: 'captain_emeritus_phi_gon', player: 'Aftermath' },
  { discord: 'dunecompetitive', player: 'Valor' },
  { discord: 'squirrlyjr', player: 'TheHaydes' },
  { discord: 'cxy7722', player: 'SeeAxeWhy' },
  { discord: '.manwe_sulimo', player: 'ManweSulimo' },
  { discord: 'bungle7422', player: 'benster' },
  { discord: 'goldeneyez.', player: 'Goldeneyes' },
  { discord: 'masterofnone2412', player: 'lfcazn' },
  { discord: 'RaveY', player: 'RaveY' },
  { discord: 'piercy_svk', player: 'Piercy' },
  { discord: 'kuen4918', player: 'HKMuadDib' },
  { discord: 'jptuck4', player: 'JPTuck4' },
  { discord: 'evindeep', player: 'evindeep' },
  { discord: 'flinesse', player: 'yukgaejang' },
  { discord: 'wakemeupbeforeyoujoho', player: 'Sabastapul' },
  { discord: 'chris6436', player: 'ChrisTheCrisp' },
  { discord: 'boma4459', player: 'BoMa85' },
  { discord: 'thiagoef', player: 'thiagomaster' },
];

const normalize = (s: string) => s.trim().toLowerCase().replace(/^[.\s]+|[.\s]+$/g, "");

export function findByDiscord(discord: string): string | null {
  const n = normalize(discord);
  if (!n) return null;
  const hit = PLAYER_DISCORD_MAP.find((r) => normalize(r.discord) === n);
  return hit ? hit.player : null;
}

export function findByPlayer(player: string): string | null {
  const n = normalize(player);
  if (!n) return null;
  const hit = PLAYER_DISCORD_MAP.find((r) => normalize(r.player) === n);
  return hit ? hit.discord : null;
}
