/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UploadRouteImport } from './routes/upload'
import { Route as TournamentRegisterRouteImport } from './routes/tournament-register'
import { Route as TournamentRouteImport } from './routes/tournament'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as StatsRouteImport } from './routes/stats'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as MatchesRouteImport } from './routes/matches'
import { Route as LedgerRouteImport } from './routes/ledger'
import { Route as LeaderboardRouteImport } from './routes/leaderboard'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as ClaimRouteImport } from './routes/claim'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RUsernameRouteImport } from './routes/r.$username'
import { Route as PlayersKeyRouteImport } from './routes/players.$key'
import { Route as AuthCallbackRouteImport } from './routes/auth_.callback'
import { Route as LeadersOriginSlugRouteImport } from './routes/leaders.$origin.$slug'

const UploadRoute = UploadRouteImport.update({
  id: '/upload',
  path: '/upload',
  getParentRoute: () => rootRouteImport,
} as any)
const TournamentRegisterRoute = TournamentRegisterRouteImport.update({
  id: '/tournament-register',
  path: '/tournament-register',
  getParentRoute: () => rootRouteImport,
} as any)
const TournamentRoute = TournamentRouteImport.update({
  id: '/tournament',
  path: '/tournament',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const StatsRoute = StatsRouteImport.update({
  id: '/stats',
  path: '/stats',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const MatchesRoute = MatchesRouteImport.update({
  id: '/matches',
  path: '/matches',
  getParentRoute: () => rootRouteImport,
} as any)
const LedgerRoute = LedgerRouteImport.update({
  id: '/ledger',
  path: '/ledger',
  getParentRoute: () => rootRouteImport,
} as any)
const LeaderboardRoute = LeaderboardRouteImport.update({
  id: '/leaderboard',
  path: '/leaderboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ClaimRoute = ClaimRouteImport.update({
  id: '/claim',
  path: '/claim',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RUsernameRoute = RUsernameRouteImport.update({
  id: '/r/$username',
  path: '/r/$username',
  getParentRoute: () => rootRouteImport,
} as any)
const PlayersKeyRoute = PlayersKeyRouteImport.update({
  id: '/players/$key',
  path: '/players/$key',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth_/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const LeadersOriginSlugRoute = LeadersOriginSlugRouteImport.update({
  id: '/leaders/$origin/$slug',
  path: '/leaders/$origin/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/claim': typeof ClaimRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/leaderboard': typeof LeaderboardRoute
  '/ledger': typeof LedgerRoute
  '/matches': typeof MatchesRoute
  '/privacy': typeof PrivacyRoute
  '/profile': typeof ProfileRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/stats': typeof StatsRoute
  '/terms': typeof TermsRoute
  '/tournament': typeof TournamentRoute
  '/tournament-register': typeof TournamentRegisterRoute
  '/upload': typeof UploadRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/players/$key': typeof PlayersKeyRoute
  '/r/$username': typeof RUsernameRoute
  '/leaders/$origin/$slug': typeof LeadersOriginSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/claim': typeof ClaimRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/leaderboard': typeof LeaderboardRoute
  '/ledger': typeof LedgerRoute
  '/matches': typeof MatchesRoute
  '/privacy': typeof PrivacyRoute
  '/profile': typeof ProfileRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/stats': typeof StatsRoute
  '/terms': typeof TermsRoute
  '/tournament': typeof TournamentRoute
  '/tournament-register': typeof TournamentRegisterRoute
  '/upload': typeof UploadRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/players/$key': typeof PlayersKeyRoute
  '/r/$username': typeof RUsernameRoute
  '/leaders/$origin/$slug': typeof LeadersOriginSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/claim': typeof ClaimRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/leaderboard': typeof LeaderboardRoute
  '/ledger': typeof LedgerRoute
  '/matches': typeof MatchesRoute
  '/privacy': typeof PrivacyRoute
  '/profile': typeof ProfileRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/stats': typeof StatsRoute
  '/terms': typeof TermsRoute
  '/tournament': typeof TournamentRoute
  '/tournament-register': typeof TournamentRegisterRoute
  '/upload': typeof UploadRoute
  '/auth_/callback': typeof AuthCallbackRoute
  '/players/$key': typeof PlayersKeyRoute
  '/r/$username': typeof RUsernameRoute
  '/leaders/$origin/$slug': typeof LeadersOriginSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/claim'
    | '/forgot-password'
    | '/leaderboard'
    | '/ledger'
    | '/matches'
    | '/privacy'
    | '/profile'
    | '/reset-password'
    | '/sitemap.xml'
    | '/stats'
    | '/terms'
    | '/tournament'
    | '/tournament-register'
    | '/upload'
    | '/auth/callback'
    | '/players/$key'
    | '/r/$username'
    | '/leaders/$origin/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/claim'
    | '/forgot-password'
    | '/leaderboard'
    | '/ledger'
    | '/matches'
    | '/privacy'
    | '/profile'
    | '/reset-password'
    | '/sitemap.xml'
    | '/stats'
    | '/terms'
    | '/tournament'
    | '/tournament-register'
    | '/upload'
    | '/auth/callback'
    | '/players/$key'
    | '/r/$username'
    | '/leaders/$origin/$slug'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/claim'
    | '/forgot-password'
    | '/leaderboard'
    | '/ledger'
    | '/matches'
    | '/privacy'
    | '/profile'
    | '/reset-password'
    | '/sitemap.xml'
    | '/stats'
    | '/terms'
    | '/tournament'
    | '/tournament-register'
    | '/upload'
    | '/auth_/callback'
    | '/players/$key'
    | '/r/$username'
    | '/leaders/$origin/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  ClaimRoute: typeof ClaimRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LeaderboardRoute: typeof LeaderboardRoute
  LedgerRoute: typeof LedgerRoute
  MatchesRoute: typeof MatchesRoute
  PrivacyRoute: typeof PrivacyRoute
  ProfileRoute: typeof ProfileRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  StatsRoute: typeof StatsRoute
  TermsRoute: typeof TermsRoute
  TournamentRoute: typeof TournamentRoute
  TournamentRegisterRoute: typeof TournamentRegisterRoute
  UploadRoute: typeof UploadRoute
  AuthCallbackRoute: typeof AuthCallbackRoute
  PlayersKeyRoute: typeof PlayersKeyRoute
  RUsernameRoute: typeof RUsernameRoute
  LeadersOriginSlugRoute: typeof LeadersOriginSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/upload': {
      id: '/upload'
      path: '/upload'
      fullPath: '/upload'
      preLoaderRoute: typeof UploadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tournament-register': {
      id: '/tournament-register'
      path: '/tournament-register'
      fullPath: '/tournament-register'
      preLoaderRoute: typeof TournamentRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tournament': {
      id: '/tournament'
      path: '/tournament'
      fullPath: '/tournament'
      preLoaderRoute: typeof TournamentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stats': {
      id: '/stats'
      path: '/stats'
      fullPath: '/stats'
      preLoaderRoute: typeof StatsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/matches': {
      id: '/matches'
      path: '/matches'
      fullPath: '/matches'
      preLoaderRoute: typeof MatchesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ledger': {
      id: '/ledger'
      path: '/ledger'
      fullPath: '/ledger'
      preLoaderRoute: typeof LedgerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leaderboard': {
      id: '/leaderboard'
      path: '/leaderboard'
      fullPath: '/leaderboard'
      preLoaderRoute: typeof LeaderboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/claim': {
      id: '/claim'
      path: '/claim'
      fullPath: '/claim'
      preLoaderRoute: typeof ClaimRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/r/$username': {
      id: '/r/$username'
      path: '/r/$username'
      fullPath: '/r/$username'
      preLoaderRoute: typeof RUsernameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/players/$key': {
      id: '/players/$key'
      path: '/players/$key'
      fullPath: '/players/$key'
      preLoaderRoute: typeof PlayersKeyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth_/callback': {
      id: '/auth_/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leaders/$origin/$slug': {
      id: '/leaders/$origin/$slug'
      path: '/leaders/$origin/$slug'
      fullPath: '/leaders/$origin/$slug'
      preLoaderRoute: typeof LeadersOriginSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  ClaimRoute: ClaimRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LeaderboardRoute: LeaderboardRoute,
  LedgerRoute: LedgerRoute,
  MatchesRoute: MatchesRoute,
  PrivacyRoute: PrivacyRoute,
  ProfileRoute: ProfileRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  StatsRoute: StatsRoute,
  TermsRoute: TermsRoute,
  TournamentRoute: TournamentRoute,
  TournamentRegisterRoute: TournamentRegisterRoute,
  UploadRoute: UploadRoute,
  AuthCallbackRoute: AuthCallbackRoute,
  PlayersKeyRoute: PlayersKeyRoute,
  RUsernameRoute: RUsernameRoute,
  LeadersOriginSlugRoute: LeadersOriginSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
