// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hyyrftnqalzarclbhedx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imh5eXJmdG5xYWx6YXJjbGJoZWR4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODM1MDAzMzMsImV4cCI6MjA5OTA3NjMzM30.KPcy0MR1X7OCGr3-HlrFhId0hL8bYvGHSBP6Qxl_0_w";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});